---
url: /
name: Perhekoti Hokkanen oy
menu:
- text: Etusivu
  url: /
- text: Kuvia
  url: /kuvia.html
- text: Riitta ja Reijo
  url: /riitta-ja-reijo.html
- text: Arvot
  url: /arvot.html
- text: Yhteystiedot
  url: /yhteystiedot.html
exclude:
  - sass
  - config.rb
  - Procfile
  - Thumbs.db
  - Gemfile
  - CNAME
markdown: kramdown
prose:
    media: images
